version: '3.3'
services:
  games:
    image: scratch
    command: sh -c "./server"
    working_dir: "/app"
    volumes:
      - "./:/app"
    environment:
      - PORT=3141
      - DB_HOST=localhost
      - DB_USER=games_user
      - DB_PASS=jg1234
      - DB_NAME=joeys_games
    network_mode: host
