version: '3.3'
services:
  games:
    image: node:16.13.1
    command: sh -c "node server.js"
    working_dir: "/app"
    volumes:
      - "./:/app"
    environment:
      - PORT=3141
      - DB_HOST=localhost
      - DB_USER=games_user
      - DB_PASS=jg1234
      - DB_NAME=joeys_games
    network_mode: host
