version: '3.3'

services:
  games:
    image: node:23.11.0
    hostname: games
    command: sh -c "node server.js"
    working_dir: "/app"
    volumes:
      - "./:/app"
    environment:
      - PORT=8080
      - DB_HOST=dbhost
      - DB_USER=dbuser
      - DB_PASS=dbpass
      - DB_NAME=dbname
